/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.sean;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int actionPanel=0x7f05000b;
        public static final int albumCover=0x7f050006;
        public static final int infoPanel=0x7f050005;
        public static final int lastSong=0x7f050002;
        public static final int nextSong=0x7f050004;
        public static final int playPause=0x7f050003;
        public static final int playbackPanel=0x7f050001;
        public static final int playlist=0x7f05000c;
        public static final int rootLayout=0x7f050000;
        public static final int songAlbum=0x7f050009;
        public static final int songArtist=0x7f05000a;
        public static final int songInfo=0x7f050007;
        public static final int songTitle=0x7f050008;
        public static final int volume=0x7f05000d;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
