/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.sean;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int album_cover=0x7f050004;
        public static final int cancel=0x7f05000f;
        public static final int connect=0x7f050010;
        public static final int host=0x7f05000b;
        public static final int last_song=0x7f050001;
        public static final int next_song=0x7f050003;
        public static final int pass=0x7f05000e;
        public static final int pc_power=0x7f050000;
        public static final int play_pause=0x7f050002;
        public static final int playlist=0x7f050009;
        public static final int port=0x7f05000c;
        public static final int song_album=0x7f050007;
        public static final int song_artist=0x7f050008;
        public static final int song_info=0x7f050005;
        public static final int song_title=0x7f050006;
        public static final int user=0x7f05000d;
        public static final int volume=0x7f05000a;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int new_connection=0x7f030001;
        public static final int volume_control=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
